[package]
name = "del"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
blake3 = "1.8.7"
clap = { version = "4.6.6", features = ["derive", "unicode", "cargo", "color"] }
dirs-next = "2.0.0"
figment = { version = "0.10.19", features = ["toml", "env"] }
rayon = "1.12.0"
rusqlite = { version = "0.40.2", features = ["bundled", "load_extension"] }
serde = { version = "1.0.229", features = ["derive"] }
tar = "0.4.46"
zstd = "0.13.3"
